### ISSUE TITLE
无法连接以及应该如何使用 chnroute？

### ISSUE THREAD

**Issue by ddqp** [MuJJus/openwrt-shadowvpn#1]
请问，这个版本的shadowvpn怎么设置chnroute？我看设置界面没有，另外我安装后，增加接口了，然后发现连接不上，用原版的luci界面是可以连接上的

**Comment by MuJJus** [comment]
LuCI 界面使用 https://github.com/MuJJus/luci-proto-shadowvpn

如果无法连接是因为安装后需要重启网络才能认到新安装的协议

关于 chnroute 的用法可以在 /etc/config/network 中添加静态路由，例如:
```
config route
        option interface 'wan'
        option target '1.1.1.0'
        option netmask '255.255.255.0'
```
也可以在 /etc/shadowvpn/(up | down).d/ 中编写你自己的启动/关闭脚本，参数说明如下:
```
#!/bin/sh

IFACE="$1"
IPADDR="$2"
NETMASK="$3"
GATEWAY="$4"
INTERFACE="$5"
```

如果在寻找一个现成的科学上网解决方案可以参考 https://github.com/MuJJus/doghole

**Comment by ddqp** [comment]
我一直用那个chnroute的文件，只是原版的shadowvpn总是有问题，经常重启后失效。

doghole，好名字，我试试啊。

谢谢你

**Comment by MuJJus** [comment]
自嘲起的名字而已。
不客气
